#!/bin/bash
#
# Copyright 2005-2007 Zach Borgerding <zborgerd@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="alacarte"
VERSION="3.10.0"
REVISION="1"

PKG_SOURCEURL='http://download.gnome.org/sources/$NAME/$VER_MAJ.$VER_MIN/$NAME-$VERSION.tar.xz'
PKG_NEEDSTATIC="configure: WARNING: unrecognized options: --disable-static"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makecheck
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
