#!/bin/sh
#
# Copyright 2005-2007 Dagmar d'Surreal <rivyqntzne@tznvy.pbz>
# Available under the terms of the GNU GPL.
#

NAME="mm-common"
VERSION="0.9.6"
REVISION="2"

PKG_SOURCEURL='http://download.gnome.org/sources/${NAME}/$VER_MAJ.$VER_MIN/${NAME}-${VERSION}.tar.xz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
