#!/bin/bash
#
# Copyright 2009 Tiago Salvador Souza
# Available under the terms of the GNU GPL.
#

NAME="gjs"
VERSION="1.38.1"
REVISION="1"

PKG_SOURCEURL='${DLG_GNOMEMIRROR}/${NAME}/${VER_MAJ}.${VER_MIN}/${NAME}-${VERSION}.tar.xz'
PKG_USEAUTOGENSH="yes please"
PKG_DISABLESMP="yes"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
#makecheck
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
