#!/bin/bash
#
# Copyright 2013 Eugene Wissner <belka.ew@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="tdb"
VERSION="1.2.12"
REVISION="1"

PKG_SOURCEURL='http://www.samba.org/ftp/$NAME/$NAME-$VERSION.tar.gz'
PKG_NEEDSTATIC="waf: error: no such option: --disable-static"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
