#!/bin/bash
#
# Copyright 2009 Tiago Salvador Souza
# Available under the terms of the GNU GPL.
#

NAME="geoclue"
VERSION="0.12.99"
REVISION="1"

PKG_SOURCEURL='http://freedesktop.org/~hadess/$NAME-$VERSION.tar.gz'
PKG_SANIFYNOTOUCH="'aclocal-1.11' is missing on your system."

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure --enable-gtk=yes 
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
