#!/bin/bash
#
# Copyright 2012 Eugene Wissner <belka.ew@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="yelp-tools"
VERSION="3.6.1"
REVISION="1"

PKG_SOURCEURL='http://ftp.gnome.org/pub/GNOME/sources/${NAME}/${VER_MAJ}.${VER_MIN}/${NAME}-${VERSION}.tar.xz'
PKG_NEEDSTATIC="unrecognized options: --disable-static"
PKG_ARCH="noarch"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
