#!/bin/bash
#
# Copyright 2008-2012 Sasa Ostrouska <saxa@droplinegnome.org>
# Available under the terms of the GNU GPL.
#

NAME="telepathy-mission-control"
VERSION="5.15.0"
REVISION="3"

PKG_SOURCEURL='http://telepathy.freedesktop.org/releases/${NAME}/${NAME}-$VERSION.tar.gz'
PKG_SANIFYNOTOUCH="1"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure --disable-debug \
	--enable-gnome-keyring
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
