#!/bin/bash
#
# Copyright 2013 Bart van der Hall
# Available under the terms of the GNU GPL.
#

NAME="openchange"
VERSION="2.0"
REVISION="1"

PKG_SOURCEURL='http://tracker.openchange.org/attachments/download/220/${NAME}-${VERSION}-QUADRANT.tar.gz'
PKG_SANIFYNOTOUCH='yes'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
