#!/bin/bash
#
# Copyright 2004-2012 Dagmar d'Surreal <rivyqntzne@tznvy.pbz>
# Available under the terms of the GNU GPL.
#

NAME="gstreamer1"
VERSION="1.2.3"
REVISION="1"

PKG_SOURCEURL='http://gstreamer.freedesktop.org/src/gstreamer/gstreamer-${VERSION}.tar.xz'
PKG_SANIFYNOTOUCH='ohh'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

PKG_DOCFILES="$PKG_DOCFILES RELEASE"

cflags
cxxflags
prepare
analyzesource
configure --enable-gtk-doc \
	--enable-profiling \
	--enable-introspection \
	--disable-tests \
	--disable-fatal-warnings \
	--with-package-name="\"Dropline Gnome GStreamer ${VERSION}"\" \
	--with-package-origin="\"http://www.droplinegnome.org"\"
make
makecheck
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
