#!/bin/bash
#
# Copyright 2009 Tyrael <tyrael@droplinegnome.org>
# Available under the terms of the GNU GPL.
#

NAME="farstream"
VERSION="0.2.3"
REVISION="2"

PKG_SOURCEURL='http://freedesktop.org/software/${NAME}/releases/${NAME}/${NAME}-${VERSION}.tar.gz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
