#!/bin/bash
#
# Copyright 2004 Dagmar d'Surreal <rivyqntzne@tznvy.pbz>
# Copyright 2006 Scott Harmon
# Available under the terms of the GNU GPL.
#

NAME="webkit"
VERSION="2.2.4"
REVISION="1"

PKG_SOURCEURL='http://webkitgtk.org/releases/${NAME}gtk-${VERSION}.tar.xz'
PKG_SANIFYNOTOUCH="1"
PKG_DISABLESMP="no parallel builds"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource

configure --enable-introspection \
	--enable-geolocation \
	--enable-gtk-doc-html=no \
	--disable-silent-rules
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
