#!/bin/bash
#
# Copyright 2004, 2007 Dagmar d'Surreal <rivyqntzne@tznvy.pbz>
# Copyright 2005, 2006, 2007 Scott Harmon
# Available under the terms of the GNU GPL.
#

NAME="vte2_90"
VERSION="0.34.9"
REVISION="1"

PKG_SOURCEURL='http://download.gnome.org/sources/vte/${VER_MAJ}.${VER_MIN}/vte-${VERSION}.tar.xz'
PKG_SANIFYNOTOUCH='iii'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
