#!/bin/bash
#
# Copyright 2005 Marius Gravdal <marius@dot42.org>
# Available under the terms of the GNU GPL.
#

NAME="libmusicbrainz5"
VERSION="5.0.1"
REVISION="2"

PKG_SOURCEURL='http://github.com/downloads/metabrainz/libmusicbrainz/libmusicbrainz-${VERSION}.tar.gz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

prepare
analyzesource

# Use cmake
spewdo "cd ${PKG_BUILDROOT}"
spewdo "cmake -DCMAKE_INSTALL_PREFIX=${PKG_PREFIX} \
   -DCMAKE_BUILD_TYPE=Release \
   -DLIB_SUFFIX='${LIBSUFFIX}' ." || exit 1

make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
