#!/bin/bash
#
# Copyright 2013 Bart van der Hall
# Available under the terms of the GNU GPL.
#

NAME="check"
VERSION="0.9.10"
REVISION="2"

PKG_SOURCEURL='http://downloads.sourceforge.net/${NAME}/${NAME}-${VERSION}.tar.gz'
PKG_SANIFYNOTOUCH='uuuu'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
