#!/bin/bash
#
# Copyright 2012 Bart van der Hall
# Available under the terms of the GNU GPL.
#

NAME="libpwquality"
VERSION="1.2.3"
REVISION="1"

PKG_SOURCEURL='https://fedorahosted.org/releases/l/i/$NAME/$NAME-$VERSION.tar.bz2'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure --with-securedir=/lib${LIBSUFFIX}/security
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
