#!/bin/bash
#
# Copyright 2005 Dagmar d'Surreal <rivyqntzne@tznvy.pbz>
# Available under the terms of the GNU GPL.
#

NAME="speex"
VERSION="1.2rc1"
REVISION="1"

PKG_SOURCEURL='http://downloads.us.xiph.org/releases/$NAME/$NAME-$VERSION.tar.gz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
