#!/bin/bash
#
# Copyright 2013 Eugene Wissner <belka.ew@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="slack-timedate"
VERSION="1.1"
REVISION="1"

PKG_SOURCEURL='http://dl.flevum.de/$NAME/$NAME-$VERSION.tar.xz'
PKG_NEEDSTATIC="not supported"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
