#!/bin/bash
#
# Copyright 2005 John M. Lang <john.m.lang@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="eog"
VERSION="3.10.2"
REVISION="1"

PKG_SOURCEURL='${DLG_GNOMEMIRROR}/${NAME}/${VER_MAJ}.${VER_MIN}/${NAME}-${VERSION}.tar.xz'
PKG_SANIFYNOTOUCH='ops'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
