#!/bin/bash
#
# Copyright 2013 Bart van der Hall
# Available under the terms of the GNU GPL.
#

NAME="spice-protocol"
VERSION="0.12.6"
REVISION="1"

PKG_SOURCEURL='http://spice-space.org/download/releases/${NAME}-${VERSION}.tar.bz2'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
