#!/bin/bash
#
# Copyright 2013 Bart van der Hall
# Available under the terms of the GNU GPL.
#

NAME="libosinfo"
VERSION="0.2.8"
REVISION="1"

PKG_SOURCEURL='https://fedorahosted.org/releases/l/i/${NAME}/${NAME}-${VERSION}.tar.gz'
PKG_SANIFYNOTOUCH='uuuu'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
