#!/bin/bash
#
# Copyright 2005, 2007 Dagmar d'Surreal <rivyqntzne@tznvy.pbz>
# Modified by Zach Borgerding <zborgerd@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="libuser"
VERSION="0.59"
REVISION="2"

PKG_SOURCEURL='http://fedorahosted.org/releases/l/i/${NAME}/${NAME}-${VERSION}.tar.xz'
PKG_SANIFYNOTOUCH="otherwise it will force an autoreconf"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

configfile /etc/libuser.conf

cflags
prepare
analyzesource
configure --enable-gtk-doc
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
