#!/bin/bash
#
# Copyright 2004,2007 Dagmar d'Surreal <rivyqntzne@tznvy.pbz>
# Copyright 2006 Scott Harmon
# Available under the terms of the GNU GPL.
#

NAME="gnome-user-docs"
VERSION="3.10.2"
REVISION="1"

PKG_SOURCEURL='${DLG_GNOMEMIRROR}/${NAME}/${VER_MAJ}.${VER_MIN}/${NAME}-${VERSION}.tar.xz'
PKG_NEEDSTATIC="unrecognized options: --disable-static"
PKG_SANIFYNOTOUCH="autotools problem"
PKG_ARCH="noarch"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
