#!/bin/bash
#
# Copyright 2005 John M. Lang <john.m.lang@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="libpeas"
VERSION="1.9.0"
REVISION="1"

PKG_SOURCEURL='http://download.gnome.org/sources/${NAME}/${VER_MAJ}.${VER_MIN}/${NAME}-${VERSION}.tar.xz'
PKG_SANIFYNOTOUCH='oh no again'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure --enable-python3
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
