#!/bin/bash
#
# Copyright 2013 Eugene Wissner <belka.ew@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="pulseaudio"
VERSION="4.0"
REVISION="1"

PKG_SOURCEURL='http://freedesktop.org/software/$NAME/releases/$NAME-$VERSION.tar.xz'
PKG_SANIFYNOTOUCH="yes"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

PKG_PATCH[0]='pulseaudio-bash-completion.diff'

cflags
prepare

applypatch 0 1

spewdo "cd $PKG_SRCROOT"
spewdo "sed -i.no_consolekit -e 's/^load-module module-console-kit/#load-module module-console-kit/' src/daemon/default.pa.in"
spewdo "sed -i -e 's|\"/lib /usr/lib|\"/lib${LIBSUFFIX} /usr/lib${LIBSUFFIX}|' configure"

analyzesource

# tcpwrap's check is broken because of a deprecated yp_get_default_domain
# reference on Slackware's libwrap.a
configure --with-system-user=pulse \
	--with-system-group=pulse \
	--with-access-group=pulse-access \
	--with-database=tdb
	--disable-rpath \
	--disable-gconf \
	--disable-hal-compat \
	--disable-esound \
	--disable-tcpwrap
make
makeinstall install-strip
tidydocumentation
analyzebinaries

# Alsa and Pulseaudio config
cat << EOF >> $PKG_STAGEROOT/etc/asound.conf
pcm.headset {
        type bluetooth
}

ctl.headset {
        type bluetooth
}

pcm.pulse {
    type pulse
}

ctl.pulse {
    type pulse
}

pcm.!default {
    type pulse
}

ctl.!default {
    type pulse
}

EOF

# Rename config files
configfile /etc/pulse/client.conf
configfile /etc/pulse/default.pa
configfile /etc/pulse/daemon.conf
configfile /etc/pulse/system.pa
configfile /etc/asound.conf

createroleaccount pulse 230 230
createroleaccount realtime 231 231
createroleaccount pulse-access 232 232

createdir $PKG_STAGEROOT$PKG_LOCALSTATEDIR/run/pulse
createdir $PKG_STAGEROOT$PKG_LOCALSTATEDIR/lib/pulse
spewdo "chmod 0700 ${PKG_STAGEROOT}/var/lib/pulse"

createdir "$PKG_STAGEROOT$PKG_DATADIR/bash-completion"
spewdo "mv $PKG_STAGEROOT$PKG_SYSCONFDIR/bash_completion.d $PKG_STAGEROOT$PKG_DATADIR/bash-completion/completions"

finalizepackage
packagize
cleanup
