#!/bin/bash
#
# Copyright 2005 Marius Gravdal <marius@dot42.org>
# Available under the terms of the GNU GPL.
#

NAME="cups-pk-helper"
VERSION="0.2.5"
REVISION="1"

PKG_SOURCEURL='http://www.freedesktop.org/software/${NAME}/releases/${NAME}-${VERSION}.tar.xz'
PKG_SANIFYNOTOUCH="1"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
