#!/bin/bash
#
# Copyright 2013 Eugene Wissner <belka.ew@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="colord-gtk"
VERSION="0.1.25"
REVISION="1"

PKG_SOURCEURL='http://www.freedesktop.org/software/colord/releases/$NAME-$VERSION.tar.xz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure --enable-introspection
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
