#!/bin/bash
#
# Copyright 2013 Bart van der Hall
# Available under the terms of the GNU GPL.
#

NAME="rdflib"
VERSION="3.1.0"
REVISION="1"

PKG_SOURCEURL='http://rdflib.googlecode.com/files/${NAME}-${VERSION}.tar.gz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

if [ "${PKG_ARCH%86}" != "$PKG_ARCH" ]; then
  PKG_ARCH=i486
fi

prepare
analyzesource

spewdo "cd $PKG_SRCROOT"
loggedcommand make "python setup.py install --prefix=$PKG_PREFIX --root=$PKG_STAGEROOT"

tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
