#!/bin/sh
#
# Copyright 2010 Sasa Ostrouska
# Available under the terms of the GNU GPL.
#

NAME="atkmm"
VERSION="2.22.7"
REVISION="2"

PKG_SOURCEURL='http://download.gnome.org/sources/${NAME}/$VER_MAJ.$VER_MIN/${NAME}-${VERSION}.tar.xz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
