#!/bin/bash
#
# Copyright 2004-2007 Dagmar d'Surreal <rivyqntzne@tznvy.pbz>
# Available under the terms of the GNU GPL.
#

NAME="gnome-menus"
VERSION="3.10.1"
REVISION="1"

PKG_SOURCEURL='http://download.gnome.org/sources/$NAME/$VER_MAJ.$VER_MIN/$NAME-$VERSION.tar.xz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure --disable-debug
make
makecheck
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
