#!/bin/sh
#
# Copyright 2013 Your name
# Available under the terms of the GNU GPL.
#

NAME="seahorse-sharing"
VERSION="3.8.0"
REVISION="2"

PKG_SOURCEURL='http://download.gnome.org/sources/${NAME}/${VER_MAJ}.${VER_MIN}/${NAME}-${VERSION}.tar.xz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
