#!/bin/bash
#
# Copyright 2011 Sasa Ostrouska <saxa@droplinegnome.org>
# Available under the terms of the GNU GPL.
#

NAME="rawstudio"
VERSION="2.0"
REVISION="5"

PKG_SOURCEURL='http://${NAME}.org/files/release/${NAME}-${VERSION}.tar.gz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
PKG_CFLAGS+=" -lgthread-2.0"
prepare
analyzesource
configure
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
