#!/bin/bash
#
# Copyright 2004-2007 Dagmar d'Surreal <rivyqntzne@tznvy.pbz>
# Available under the terms of the GNU GPL.
#

NAME="libsigc++"
VERSION="2.2.11"
REVISION="2"

PKG_SOURCEURL='http://download.gnome.org/sources/libsigc++/$VER_MAJ.$VER_MIN/$NAME-$VERSION.tar.xz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure --without-libstdc-doc
make
makecheck
makeinstall install-strip

# No reaction on --docdir
createdir $PKG_STAGEROOT$PKG_DOCDIR
spewdo "mv $PKG_STAGEROOT$PKG_PREFIX/share/doc/$NAME-$VER_MAJ.0/* $PKG_STAGEROOT$PKG_DOCDIR"
removedir $PKG_STAGEROOT$PKG_PREFIX/share/doc

tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
