#!/bin/bash
#
# Copyright 2010 Sasa Ostrouska
# Available under the terms of the GNU GPL.
#

NAME="rygel"
VERSION="0.20.3"
REVISION="1"

PKG_SOURCEURL='${DLG_GNOMEMIRROR}/${NAME}/${VER_MAJ}.${VER_MIN}/${NAME}-${VERSION}.tar.xz'
PKG_SANIFYNOTOUCH="1"
PKG_DISABLESMP="1"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure --enable-gst-launch-plugin
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
