#!/bin/bash
#
# Copyright 2005 John M. Lang <john.m.lang@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="gthumb"
VERSION="3.2.6"
REVISION="1"

PKG_SOURCEURL='${DLG_GNOMEMIRROR}/$NAME/$VER_MAJ.$VER_MIN/$NAME-$VERSION.tar.xz'
PKG_SANIFYNOTOUCH="1"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure --enable-libopenraw
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
