#!/bin/bash
#
# Copyright 2004 Dagmar d'Surreal <rivyqntzne@tznvy.pbz>
# Available under the terms of the GNU GPL.
#

NAME="totem"
VERSION="3.10.0"
REVISION="1"

PKG_SOURCEURL='http://download.gnome.org/sources/${NAME}/${VER_MAJ}.${VER_MIN}/${NAME}-${VERSION}.tar.xz'
PKG_SANIFYNOTOUCH="VALAC error"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure --enable-nautilus \
	--enable-browser-plugins \
	--enable-vala \
	--enable-gmp-plugin \
	--enable-narrowspace-plugin \
	--enable-mully-plugin \
	--enable-cone-plugin \
	--enable-gtk-doc \
	--enable-vegas-plugin \
	--enable-python
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
