#!/bin/bash
#
# Copyright 2012 Bart van der Hall <bartgymnast@hotmail.com>
# Available under the terms of the GNU GPL.
#

NAME="gnome-video-effects"
VERSION="0.4.0"
REVISION="2"

PKG_SOURCEURL='http://download.gnome.org/sources/$NAME/$VER_MAJ.$VER_MIN/$NAME-$VERSION.tar.xz'
PKG_NEEDSTATIC="--disable-static unrecognized option"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure
make
makecheck
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
