#!/bin/bash
#
# Copyright 2009 Eugene Wissner <belka.ew@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="alsa-plugins"
VERSION="1.0.27"
REVISION="3"

PKG_SOURCEURL='http://alsa.cybermirror.org/plugins/${NAME}-${VERSION}.tar.bz2'
PKG_SANIFYNOTOUCH="yes"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

PKG_PATCH[0]='alsa-plugins-avcodec-check.patch'

cflags
cxxflags
prepare

applypatch 0 1

analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
