#!/bin/bash
#
# Copyright 2013 Bart van der Hall
# Available under the terms of the GNU GPL.
#

NAME="spice-gtk"
VERSION="0.21"
REVISION="1"

PKG_SOURCEURL='http://spice-space.org/download/gtk/${NAME}-${VERSION}.tar.bz2'
PKG_SANIFYNOTOUCH='indeed'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure --disable-smartcard
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
