#!/bin/bash
#
# Copyright 2013 Eugene Wissner <belka.ew@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="colord"
VERSION="1.0.2"
REVISION="1"

PKG_SOURCEURL='http://www.freedesktop.org/software/$NAME/releases/$NAME-$VERSION.tar.xz'
PKG_SANIFYNOTOUCH='yey'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

# bash-completion from slackware extra repository is needed

cflags
prepare
analyzesource
configure --disable-examples \
	--disable-systemd-login \
	--with-daemon-user=colord \
	--enable-vala

make
makeinstall install-strip

createroleaccount colord 71 71

# Moving udev rules into their place.
spewdo "mv $PKG_STAGEROOT/lib/udev $PKG_STAGEROOT$PKG_SYSCONFDIR"
spewdo "rmdir $PKG_STAGEROOT/lib"

tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
