#!/bin/bash
#
# Copyright 2008 Sasa Ostrouska <saxa@droplinegnome.org>
# Available under the terms of the GNU GPL.
#

NAME="vinagre"
VERSION="3.10.2"
REVISION="1"

PKG_SOURCEURL='${DLG_GNOMEMIRROR}/${NAME}/${VER_MAJ}.${VER_MIN}/${NAME}-${VERSION}.tar.xz'
PKG_NEEDSTATIC="configure: Warning: unrecognized options: --disable-static"
PKG_SANIFYNOTOUCH='oo'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure --enable-ssh
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
