#!/bin/bash
#
# Copyright 2013 Bart van der Hall
# Available under the terms of the GNU GPL.
#

NAME="tevent"
VERSION="0.9.19"
REVISION="1"

PKG_SOURCEURL='http://www.samba.org/ftp/${NAME}/${NAME}-${VERSION}.tar.gz'
PKG_NEEDSTATIC='unrecognized option'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource

export PYTHON=python3

configure
make
makeinstall

export PYTHON=python

tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
