#!/bin/bash
#
# Copyright 2013 Eugene Wissner <belka.ew@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="accountsservice"
VERSION="0.6.35"
REVISION="1"

PKG_SOURCEURL='http://www.freedesktop.org/software/accountsservice/$NAME-$VERSION.tar.xz'
PKG_SANIFYNOTOUCH="hm"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
