#!/bin/bash
#
# Copyright 2006 Paul Best <paul.best@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="evince"
VERSION="3.10.3"
REVISION="1"

PKG_SOURCEURL='${DLG_GNOMEMIRROR}/$NAME/$VER_MAJ.$VER_MIN/$NAME-$VERSION.tar.xz'
PKG_SANIFYNOTOUCH='yes'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource

configure --enable-tiff \
	  --enable-djvu \
	  --enable-comics \
	  --enable-nautilus \
	  --enable-xps \
	  --enable-gtk-doc \
	  --enable-introspection
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
