#!/bin/bash
#
# Copyright 2010-2012 Sasa Ostrouska <saxa@droplinegnome.org>
# Available under the terms of the GNU GPL.
#

NAME="folks"
VERSION="0.9.5"
REVISION="2"

PKG_SOURCEURL='http://download.gnome.org/sources/${NAME}/${VER_MAJ}.${VER_MIN}/${NAME}-${VERSION}.tar.xz'
PKG_SANIFYNOTOUCH="1"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure --enable-eds-backend \
	--enable-vala \
	--enable-libsocialweb-backend \
	--enable-zeitgeist \
	--enable-tracker-backend \
	--disable-fatal-warnings
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
