#!/bin/bash
#
# Copyright 2006 Paul Blazejowski <paulb@blazebox.homeip.net>
# Available under the terms of the GNU GPL.
#

NAME="zope.interface"
VERSION="4.0.2"
REVISION="1"

PKG_SOURCEURL='http://pypi.python.org/packages/source/z/${NAME}/${NAME}-${VERSION}.tar.gz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

# This package gets it's CFLAGS info from what was compiled into Python.
# Changing this variable is mainly a formality caused by this.
if [ "${PKG_ARCH%86}" != "$PKG_ARCH" ]; then
	PKG_ARCH=i486
fi

PKG_LOCALSTATEDIR=/var

cflags
cxxflags
prepare
analyzesource

spewdo "cd $PKG_SRCROOT"
spewdo "python setup.py install --prefix=$PKG_PREFIX --root=$PKG_STAGEROOT"

tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
