#!/bin/bash
#
# Copyright 2012-2013 Eugene Wissner <belka.ew@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="cogl"
VERSION="1.16.2"
REVISION="1"

PKG_SOURCEURL='$DLG_GNOMEMIRROR/$NAME/$VER_MAJ.$VER_MIN/$NAME-$VERSION.tar.xz'
PKG_SANIFYNOTOUCH='yes'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure --enable-xlib-egl-platform
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
