#!/bin/bash
#
# Copyright 2013 Eugene Wissner <belka.ew@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="gtk+3"
VERSION="3.10.7"
REVISION="1"

PKG_SOURCEURL='$DLG_GNOMEMIRROR/gtk+/$VER_MAJ.$VER_MIN/gtk+-$VERSION.tar.xz'
# Copy only the latest ChangeLog
PKG_DOCFILES=`echo "$PKG_DOCFILES" | sed -e 's/ChangeLog\*/ChangeLog/'`
PKG_SANIFYNOTOUCH="something about geninclude..."

PKG_PATCH[0]='update-gtk-immodules-3.0'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource

# Regenerate ./configure:
spewdo "cd $PKG_SRCROOT"
libtoolize --copy --force
autoreconf -vif
# Autoconf changes linux to linux-gnu.
# Our host is $ARCH-slackware-linux not $ARCH-slackware-linux-gnu:
spewdo "cd $PKG_SRCROOT/build-aux; sed -i -e 's#linux|linux-gnu|#linux|linux|#' config.sub"

if [ "$DLG_ARCH" == "x86-64" ]; then
	host="x86_64-slackware-linux"
else
	host="i486-slackware-linux"
fi

configure --enable-xkb \
	--enable-packagekit=no \
	--enable-introspection \
	--enable-xrandr \
	--enable-broadway-backend \
	--enable-x11-backend \
	--enable-xinerama \
	--build=$host
make

ls /var/log/packages/gtk+3-${VER_MAJ}.${VER_MIN}* &> /dev/null
if [ $? -eq 0 ]
then
	makecheck
fi
makeinstall install-strip

# Don't clobber im-multipress.conf
configfile $PKG_SYSCONFDIR/gtk-3.0/im-multipress.conf

# Install a "starter" gtkrc
spewdo "echo 'gtk-theme-name=\"Adwaita\"' > $PKG_STAGEROOT$PKG_SYSCONFDIR/gtk-3.0/gtkrc"
configfile $PKG_SYSCONFDIR/gtk-3.0/gtkrc

# We need to have separate 32-bit and 64-bit binaries
# for places where we have two copies of the GTK+ package installed.
# (we might have x86_64 and i486 packages on the same system, for example.)
case "$host" in
  s390x*|x86_64*)
   mv $PKG_STAGEROOT$PKG_PREFIX/bin/gtk-query-immodules-3.0{,-64}
   ( cd $PKG_STAGEROOT$PKG_PREFIX/bin
     ln -sf gtk-query-immodules-3.0-64 gtk-query-immodules-3.0
   )
   ;;
  *)
   mv $PKG_STAGEROOT$PKG_PREFIX/bin/gtk-query-immodules-3.0{,-32}
   ( cd $PKG_STAGEROOT$PKG_PREFIX/bin
     ln -sf gtk-query-immodules-3.0-32 gtk-query-immodules-3.0
   )
   ;;
esac

# Install wrappers for the binaries:
findpatch filename ${PKG_PATCH[0]}
spewdo "install -m 0755 -o root -g root $filename $PKG_STAGEROOT$PKG_PREFIX/bin/"

tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
