#!/bin/bash
#
# Copyright 2005 Paul Blazejowski <paulb@blazebox.homeip.net>
# Available under the terms of the GNU GPL.
#

NAME="NetworkManager-openconnect"
VERSION="0.9.8.4"
REVISION="1"

PKG_SOURCEURL='$DLG_GNOMEMIRROR/${NAME}/${VER_MAJ}.${VER_MIN}/${NAME}-${VERSION}.tar.xz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure --with-gtkver=3 \
	--disable-more-warnings
make
makecheck
makeinstall install-strip

createroleaccount nm-openconnect  240 240
createdir $PKG_STAGEROOT$PKG_LOCALSTATEDIR/log/nm-openconnect

tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
