#!/bin/sh
#
# Copyright 2004-2007 Dagmar d'Surreal <rivyqntzne@tznvy.pbz>
# Available under the terms of the GNU GPL.
#

NAME="py3cairo"
VERSION="1.10.0"
REVISION="1"

PKG_SOURCEURL='http://cairographics.org/releases/pycairo-$VERSION.tar.bz2'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource

OLD_PYTHON=$PYTHON
export PYTHON="python3"

# Here we run the waf configure command.
spewdo "cd $PKG_BUILDROOT ; python3 ./waf configure --prefix=/usr --libdir=$PKG_PREFIX/lib$LIBSUFFIX"

# Here we run the waf make command
spewdo "cd $PKG_BUILDROOT ; python3 ./waf build"

# Here we run the waf install command
spewdo "cd $PKG_BUILDROOT ; python3 ./waf install --destdir=$PKG_STAGEROOT"

PYTHON=$OLD_PYTHON

tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
