#!/bin/bash
#
# Copyright 2004 Todd Kulesza <todd@dropline.net>
# Available under the terms of the GNU GPL.
#

NAME="ekiga"
VERSION="4.0.1"
REVISION="3"

PKG_SOURCEURL='http://ftp.gnome.org/pub/GNOME/sources/$NAME/$VER_MAJ.$VER_MIN/$NAME-$VERSION.tar.xz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure --enable-dbus \
	--disable-scrollkeeper \
	--disable-gconf
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
