#!/bin/bash
#
# Copyright 2009 Tiago Salvador Souza
# Available under the terms of the GNU GPL.
#

NAME="geoclue2"
VERSION="2.0.0"
REVISION="1"

PKG_SOURCEURL='http://www.freedesktop.org/software/geoclue/releases/${VER_MAJ}.${VER_MIN}/geoclue-${VERSION}.tar.xz'
PKG_SANIFYNOTOUCH="'aclocal-1.11' is missing on your system."

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
