#!/bin/bash
#
# Copyright 2013 Bart van der Hall
# Available under the terms of the GNU GPL.
#

NAME="seed"
VERSION="3.8.1"
REVISION="2"

PKG_SOURCEURL='http://download.gnome.org/sources/${NAME}/${VER_MAJ}.${VER_MIN}/${NAME}-${VERSION}.tar.xz'
PKG_SANIFYNOTOUCH='uoo'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure --with-webkit=3.0
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
