#!/bin/bash
#
# Copyright 2008 Tiago Souza <ts.salvador@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="graphviz"
VERSION="2.34.0"
REVISION="1"

PKG_SOURCEURL='http://www.graphviz.org/pub/${NAME}/stable/SOURCES/${NAME}-${VERSION}.tar.gz'
PKG_SANIFYNOTOUCH='oops'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure --enable-php=no
make
makeinstall 
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup

