#!/bin/bash
#
# Copyright 2010 Sasa Ostrouska
# Available under the terms of the GNU GPL.
#

NAME="libwpg"
VERSION="0.2.2"
REVISION="2"

PKG_SOURCEURL='http://downloads.sourceforge.net/project/${NAME}/${NAME}/${NAME}-${VERSION}/${NAME}-${VERSION}.tar.xz'
PKG_SANIFYNOTOUCH='iii'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
