#!/bin/bash
#
# Copyright 2010 Sasa Ostrouska
# Available under the terms of the GNU GPL.
#

NAME="telepathy-butterfly"
VERSION="0.5.15"
REVISION="2"

PKG_SOURCEURL='http://telepathy.freedesktop.org/releases/${NAME}/${NAME}-${VERSION}.tar.gz'
PKG_SANIFYNOTOUCH="1"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
