#!/bin/bash
#
# Copyright 2004,2007 Dagmar d'Surreal <rivyqntzne@tznvy.pbz>
# Copyright 2006 Scott Harmon
# Copyright 2012 Eugene Wissner <belka.ew@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="gnome-control-center"
VERSION="3.10.2"
REVISION="2"

PKG_SOURCEURL='${DLG_GNOMEMIRROR}/$NAME/$VER_MAJ.$VER_MIN/$NAME-$VERSION.tar.xz'
PKG_SANIFYNOTOUCH='ups'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
