#!/bin/bash
#
# Copyright 2008 Renato Cunha
# Available under the terms of the GNU GPL.
#

NAME="readline"
VERSION="5.2"
REVISION="1"

PKG_SOURCEURL='ftp://ftp.gnu.org/gnu/${NAME}/${NAME}-${VERSION}.tar.gz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

PKG_PATCH[0]='readline-patches.patch'

cflags
cxxflags
prepare

applypatch 0 0

analyzesource
configure --libdir=/usr/lib${LIBSUFFIX} \
	--with-curses \
	--enable-multibyte \
	--infodir=/usr/info

make SHLIB_LIBS=-lncurses
make static
make shared
makeinstall

#createdir $PKG_STAGEROOT/usr/lib${LIBSUFFIX}
#spewdo "mv -v $PKG_STAGEROOT/lib${LIBSUFFIX}/lib{readline,history}.a $PKG_STAGEROOT/usr/lib${LIBSUFFIX}"

#spewdo "rm -v $PKG_STAGEROOT/lib${LIBSUFFIX}/lib{readline,history}.so"
#spewdo "ln -sfv ../../lib${LIBSUFFIX}/libreadline.so.5 $PKG_STAGEROOT/usr/lib${LIBDIRSUFFIX}/libreadline.so"
#spewdo "ln -sfv ../../lib${LIBSUFFIX}/libhistory.so.5 $PKG_STAGEROOT/usr/lib${LIBDIRSUFFIX}/libhistory.so"

spewdo "chmod 755 $PKG_STAGEROOT/usr/lib${LIBSUFFIX}/lib*.so.*"

tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
