#!/bin/bash
#
# Copyright 2013 Bart van der Hall <bartgymnast@hotmail.com>
# Available under the terms of the GNU GPL.
#

NAME="libquvi-scripts"
VERSION="0.4.16"
REVISION="1"

PKG_SOURCEURL='http://downloads.sourceforge.net/quvi/${NAME}-${VERSION}.tar.xz'


. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
