#!/bin/bash
#
# Copyright 2008 Sasa Ostrouska <>
# Available under the terms of the GNU GPL.
#

NAME="telepathy-gabble"
VERSION="0.18.1"
REVISION="1"

PKG_SOURCEURL='http://telepathy.freedesktop.org/releases/$NAME/$NAME-$VERSION.tar.gz'
PKG_SANIFYNOTOUCH="1"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure --with-ca-certificates=/etc/ssl/certs
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
