#!/bin/bash
#
# Copyright 2008 Zach Borgerding <zborgerd@gmail.com>
# Copyright 2013 Eugene Wissner <belka.ew@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="libcanberra"
VERSION="0.30"
REVISION="1"

PKG_SOURCEURL='http://0pointer.de/lennart/projects/$NAME/$NAME-$VERSION.tar.xz'
PKG_SANIFYNOTOUCH="Otherwise it will force an autoreconf"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base


cflags
cxxflags
prepare
analyzesource
configure --disable-oss \
	--enable-gstreamer \
	--enable-alsa \
	--enable-pulseaudio
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
