#!/bin/bash
#
# Copyright 2005, 2007-2008 Dagmar d'Surreal <rivyqntzne@tznvy.pbz>
# Available under the terms of the GNU GPL.
#

NAME="pygobject3"
VERSION="3.10.2"
REVISION="1"

PKG_SOURCEURL='$DLG_GNOMEMIRROR/pygobject/$VER_MAJ.$VER_MIN/pygobject-$VERSION.tar.xz'
PKG_SANIFYNOTOUCH='yes'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure --with-python=python2
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
