#!/bin/bash
#
# Copyright 2005 Daga <daga@daga.dyndns.org>
# Available under the terms of the GNU GPL.
#

NAME="gdl"
VERSION="3.10.0"
REVISION="1"

PKG_SOURCEURL='http://download.gnome.org/sources/$NAME/$VER_MAJ.$VER_MIN/$NAME-$VERSION.tar.xz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
