#!/bin/bash
#
# Copyright 2005 Marius Gravdal <marius@dot42.org>
# Available under the terms of the GNU GPL.
#

NAME="raw-thumbnailer"
VERSION="3.0.0"
REVISION="1"

PKG_SOURCEURL='http://libopenraw.freedesktop.org/download/${NAME}-${VERSION}.tar.bz2'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
