#!/bin/bash
#
# Copyright 2010-2012 Sasa Ostrouska <saxa@droplinegnome.org>
# Available under the terms of the GNU GPL.
#

NAME="telepathy-logger"
VERSION="0.8.0"
REVISION="2"

PKG_SOURCEURL='http://telepathy.freedesktop.org/releases/${NAME}/${NAME}-${VERSION}.tar.bz2'
PKG_SANIFYNOTOUCH="1"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
