#!/bin/bash
#
# Copyright 2012 Eugene Wissner <belka.ew@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="libopenraw"
VERSION="0.0.9"
REVISION="2"

PKG_SOURCEURL='http://${NAME}.freedesktop.org/download/${NAME}-${VERSION}.tar.bz2'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
