#!/bin/bash
#
# Copyright 2005-2007 Dagmar d'Surreal <rivyqntzne@tznvy.pbz>
# Available under the terms of the GNU GPL.
#

NAME="glibmm2"
VERSION="2.38.1"
REVISION="1"

PKG_SOURCEURL='${DLG_GNOMEMIRROR}/glibmm/$VER_MAJ.$VER_MIN/glibmm-$VERSION.tar.xz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

# buildrequires libsigc++2

cflags
cxxflags
prepare
analyzesource
configure
make
makecheck
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
