#!/bin/bash
#
# Copyright 2013 Bart van der Hall
# Available under the terms of the GNU GPL.
#

NAME="ldb"
VERSION="1.1.16"
REVISION="1"

PKG_SOURCEURL='http://www.samba.org/ftp/${NAME}/${NAME}-${VERSION}.tar.gz'
PKG_NEEDSTATIC='unrecognized option'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
