#!/bin/sh
#
# Copyright 2005 Paul Blazejowski <paulb@blazebox.homeip.net>
# Available under the terms of the GNU GPL.
#

NAME="dropline-installer"
VERSION="3.8_r4490"
REVISION="1"
PKG_SOURCEURL='http://www.droplinegnome.org/files/3.8/sources/$NAME-$VERSION.tar.bz2'
PKG_SOURCEMD5=''


PKG_PATCH[0]="dlg-applet-makefile-fix.patch"
PKG_PATCH[1]="dropline-installer.app"
PKG_PATCH[2]="dropline-installer.pam"
PKG_PATCH[3]="pkgtool.app"
PKG_PATCH[4]="pkgtool.desktop"
PKG_PATCH[5]="pkgtool.pam"
PKG_PATCH[6]="pkgtool.png"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base


cflags 
cxxflags 
prepare
applypatch 0 1
analyzesource

if [ "$DLG_ARCH" == "i686" ]; then
	configure
else
	configure --libdir=/usr/lib64
fi 

make 
makecheck
makeinstall install-strip

# Some files get copied this way
createdir $PKG_STAGEROOT/etc/pam.d
createdir $PKG_STAGEROOT/etc/security
createdir $PKG_STAGEROOT/etc/security/console.apps

findpatch filename dropline-installer.pam
spewdo "cp $filename $PKG_STAGEROOT/etc/pam.d/dropline-installer"
findpatch filename pkgtool.pam
spewdo "cp $filename $PKG_STAGEROOT/etc/pam.d/pkgtool"
findpatch filename dropline-installer.app
spewdo "cp $filename $PKG_STAGEROOT/etc/security/console.apps/dropline-installer"
findpatch filename pkgtool.app
spewdo "cp $filename $PKG_STAGEROOT/etc/security/console.apps/pkgtool"
findpatch filename pkgtool.png
spewdo "cp $filename $PKG_STAGEROOT$PKG_PREFIX/share/pixmaps/pkgtool.png"

tidydocumentation

# Fix doc directory contents
spewdo "cp $PKG_STAGEROOT$PKG_PREFIX/doc/$NAME/* $PKG_STAGEROOT$PKG_PREFIX/doc/$NAME-$VERSION"
removedir $PKG_STAGEROOT$PKG_PREFIX/doc/$NAME

analyzebinaries
finalizepackage
packagize
cleanup

