#!/bin/bash
#
# Copyright 2013 Bart van der Hall <bartgymnast@hotmail.com>
# Available under the terms of the GNU GPL.
#

NAME="python3"
VERSION="3.3.2"
REVISION="1"

PKG_SOURCEURL='http://python.org/ftp/python/${VERSION}/Python-${VERSION}.tar.xz'
PKG_DISABLESMP="yey"

PKG_PATCH[0]="python3.readline.set_pre_input_hook.diff"
PKG_PATCH[1]="python3.no-static-library.diff"
PKG_PATCH[2]="python3.x86_64.diff"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base


if [ "$DLG_ARCH" == "x86-64" ]; then
        host="x86_64-slackware-linux"
else
        host="i486-slackware-linux"
fi

cflags
cxxflags
prepare
analyzesource

applypatch 0 1
applypatch 1 1

if [ "$DLG_ARCH" = "x86-64" ]; then
  # Install to lib64 instead of lib:
applypatch 2 1
fi

# Fix python3 path in cgi.py.
spewdo "sed -i '1s|^#.*/usr/local/bin/python|#!/usr/bin/python3|' Lib/cgi.py"

configure --libdir=/usr/lib$LIBSUFFIX \
	--with-threads \
	--enable-ipv6 \
	--enable-shared \
	--with-system-expat \
	--with-system-ffi \
	--build=$host
make
makeinstall altinstall

# Create a few useful symlinks.
( cd $PKG_STAGEROOT/usr/bin
  ln -sf python3.3 python3
  ln -sf python3.3*-config python3.3-config
  ln -sf python3.3m-config python3-config
  ln -sf pydoc3.3 pydoc3
  ln -sf pyvenv-3.3 pyvenv
  ln -sf idle3.3 idle3
)

# Create symlink for python headers.
( cd $PKG_STAGEROOT/usr/include
  ln -sf python3.3m python3.3
)

# We'll install the python-tools under site-packages:
createdir $PKG_STAGEROOT/usr/lib${LIBSUFFIX}/python3.3/site-packages
spewdo "cp -a $PKG_SRCROOT/Tools/* $PKG_STAGEROOT/usr/lib${LIBSUFFIX}/python3.3/site-packages"

tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
