#!/bin/bash
#
# Copyright 2009 Tyrael <tyrael@droplinegnome.org>
# Available under the terms of the GNU GPL.
#

NAME="clutter"
VERSION="1.16.4"
REVISION="1"

PKG_SOURCEURL='$DLG_GNOMEMIRROR/$NAME/${VER_MAJ}.${VER_MIN}/$NAME-$VERSION.tar.xz'
PKG_SANIFYNOTOUCH="UFFFF"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure --enable-xinput \
	--enable-introspection=yes \
	--enable-gtk-doc
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
