#!/bin/bash
#
# Copyright 2005 Paul Blazejowski <paulb@blazebox.homeip.net>
# Copyright 2005 Scott Harmon
# Available under the terms of the GNU GPL.
#

NAME="liferea"
VERSION="1.10.2"
REVISION="1"

PKG_SOURCEURL='http://$DLG_SFMIRROR.dl.sourceforge.net/sourceforge/$NAME/$NAME-$VERSION.tar.bz2'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

PKG_PATCH[0]='add_files_to_potfiles.patch'

cflags
cxxflags
prepare

applypatch 0 1

analyzesource
configure
make
makecheck
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
