#!/bin/bash
#
# Copyright 2004-2007 Dagmar d'Surreal <rivyqntzne@tznvy.pbz>
# Available under the terms of the GNU GPL.
#

NAME="setuptools"
VERSION="1.1.6"
REVISION="1"

PKG_SOURCEURL='https://pypi.python.org/packages/source/s/${NAME}/${NAME}-${VERSION}.tar.gz'


. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

if [ "${PKG_ARCH%86}" != "$PKG_ARCH" ]; then
  PKG_ARCH=i486
fi

prepare
analyzesource

spewdo "cd $PKG_SRCROOT"
loggedcommand make "python3 setup.py install --prefix=$PKG_PREFIX --root=$PKG_STAGEROOT"

tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
