#!/bin/sh
#
# Copyright 2013 Sasa Ostrouska <saxa@droplinegnome.org>
# Available under the terms of the GNU GPL.
#

NAME="libwebp"
VERSION="0.3.1"
REVISION="1"

PKG_SOURCEURL='https://webp.googlecode.com/files/${NAME}-${VERSION}.tar.gz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
