#!/bin/sh
#
# Copyright 2004 Dagmar d'Surreal <rivyqntzne@tznvy.pbz>
# Copyright 2005, 2006 Scott Harmon
# Available under the terms of the GNU GPL.
#

NAME="gedit-plugins"
VERSION="3.10.1"
REVISION="1"

PKG_SOURCEURL='${DLG_GNOMEMIRROR}/$NAME/$VER_MAJ.$VER_MIN/$NAME-$VERSION.tar.xz'
PKG_SANIFYNOTOUCH='yes'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
