#!/bin/bash
#
# Copyright 2010 Sasa Ostrouska
# Available under the terms of the GNU GPL.
#

NAME="gdk-pixbuf2"
VERSION="2.30.5"
REVISION="1"

PKG_SOURCEURL='$DLG_GNOMEMIRROR/gdk-pixbuf/${VER_MAJ}.${VER_MIN}/gdk-pixbuf-${VERSION}.tar.xz'

PKG_PATCH[0]='gdk-pixbuf.pnglz.diff'
PKG_PATCH[1]='update-gdk-pixbuf-loaders'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

PKG_DOCDIR="$DLG_DOCDIR/gdk-pixbuf-$VERSION"
PKG_SANIFYNOTOUCH="You broke my balls."

cflags
cxxflags
prepare

applypatch 0 1

analyzesource
configure --enable-introspection \
       --with-x11
make
makeinstall

# We need to have separate 32-bit and 64-bit binaries
# for places where we have two copies of the GTK+ package installed.
# (we might have x86_64 and i486 packages on the same system, for example.)
if [ "$DLG_ARCH" == "x86-64" ]; then
   spewdo "mv $PKG_STAGEROOT$PKG_PREFIX/bin/gdk-pixbuf-query-loaders{,-64}"
   ( spewdo "cd $PKG_STAGEROOT$PKG_PREFIX/bin"
     spewdo "ln -sf gdk-pixbuf-query-loaders-64 gdk-pixbuf-query-loaders"
   )
else
   spewdo "mv $PKG_STAGEROOT$PKG_PREFIX/bin/gdk-pixbuf-query-loaders{,-32}"
   ( spewdo "cd $PKG_STAGEROOT$PKG_PREFIX/bin"
     spewdo "ln -sf gdk-pixbuf-query-loaders-32 gdk-pixbuf-query-loaders"
   )
fi

# Install wrappers for the binaries:
findpatch filename ${PKG_PATCH[1]}
spewdo "install -m 0755 $filename $PKG_STAGEROOT$PKG_PREFIX/bin/"

tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
