#!/bin/bash
#
# Copyright 2005-2006 Paul Blazejowski and Zach Borgerding
# Available under the terms of the GNU GPL.
#

NAME="cracklib"
VERSION="2.9.0"
REVISION="1"

PKG_SOURCEURL='http://$DLG_SFMIRROR.dl.sourceforge.net/sourceforge/$NAME/$NAME-$VERSION.tar.gz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure --libdir=/lib$LIBSUFFIX \
	--with-default-dict=/var/cache/cracklib/cracklib_dict 
make
makecheck
makeinstall install-strip
tidydocumentation
analyzebinaries

# install the wordlist 
createdir $PKG_STAGEROOT/var/cache/cracklib

finalizepackage
packagize
cleanup
