#!/bin/bash
#
# Copyright 2013 Eugene Wissner <belka.ew@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="PackageKit"
VERSION="0.8.15_6111975"
REVISION="1"

PKG_SOURCEURL='http://dl.flevum.de/slack-timedate/${NAME}-${VERSION}.tar.xz'
PKG_SANIFYNOTOUCH="too"
PKG_USEAUTOGENSH="git"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare

# Insert a properly mirror into the configuration file
if [ "$DLG_ARCH" == "x86-64" ]; then
	spewdo "sed -i '1 c\
[dropline]\n\
Mirror=http://belka.droplinegnome.org/3.10/x86-64/\n\
IndexFile=http://belka.droplinegnome.org/3.10/Dropline64Files3.10
	' $PKG_SRCROOT/backends/katja/Katja.conf.in"
else
	spewdo "sed -i '1 c\
[dropline]\n\
Mirror=http://belka.droplinegnome.org/3.10/i686/\n\
IndexFile=http://belka.droplinegnome.org/3.10/DroplineFiles3.10
	' $PKG_SRCROOT/backends/katja/Katja.conf.in"
fi

analyzesource

configure --enable-katja \
	--with-default-backend=katja \
	--disable-systemd \
	--disable-systemd-updates

make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
