#!/bin/bash
#
# Copyright 2005 Marius Gravdal <marius@dot42.org>
# Available under the terms of the GNU GPL.
#

NAME="libnice"
VERSION="0.1.4"
REVISION="2"

PKG_SOURCEURL='http://nice.freedesktop.org/releases/${NAME}-${VERSION}.tar.gz'
PKG_SANIFYNOTOUCH="1"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
