#!/bin/bash
#
# Copyright 2013 Bart van der Hall
# Available under the terms of the GNU GPL.
#

NAME="celt051"
VERSION="0.5.1.3"
REVISION="3"

PKG_SOURCEURL='http://downloads.xiph.org/releases/celt/celt-${VERSION}.tar.gz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
