#!/bin/bash
#
# Copyright 2007 Scott Harmon
# Available under the terms of the GNU GPL.
#

NAME="tracker"
VERSION="0.16.4"
REVISION="1"

PKG_SOURCEURL='$DLG_GNOMEMIRROR/${NAME}/${VER_MAJ}.${VER_MIN}/${NAME}-${VERSION}.tar.xz'
PKG_SANIFYNOTOUCH="1"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure --disable-unit-tests \
	--enable-miner-firefox=no \
	--enable-miner-thunderbird=no \
	--enable-miner-evolution=no \
	--enable-miner-flickr=no \
	--disable-nautilus-extension \
	--disable-tracker-needle \
	--disable-tracker-preferences \
	--disable-tracker-search-bar \
	--disable-tracker-explorer
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
