#!/bin/bash
#
# Copyright 2011 Sasa Ostrouska <saxa@droplinegnome.org>
# Available under the terms of the GNU GPL.
#

NAME="flickcurl"
VERSION="1.25"
REVISION="1"

PKG_SOURCEURL='http://download.dajobe.org/${NAME}/${NAME}-${VERSION}.tar.gz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
