#!/bin/bash
#
# Copyright 2006 Paul Best <paul.best@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="rhythmbox"
VERSION="3.0.1"
REVISION="1"

PKG_SOURCEURL='http://download.gnome.org/sources/$NAME/$VER_MAJ.$VER_MIN/$NAME-$VERSION.tar.xz'
PKG_SANIFYNOTOUCH='FIXME'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource

configure --enable-python \
	--enable-vala \
	--enable-browser-plugin \
	--with-brasero
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
