#!/bin/bash
#
# Copyright 2013 Eugene Wissner <belka.ew@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="p11-kit"
VERSION="0.20.1"
REVISION="1"

PKG_SOURCEURL='http://p11-glue.freedesktop.org/releases/$NAME-$VERSION.tar.gz'
PKG_SANIFYNOTOUCH='yes'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure
make
makeinstall install-strip

# Create the module dir
createdir $PKG_STAGEROOT/etc/pkcs11/modules

tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
