#!/bin/bash
#
# Copyright 2005, 2006 Scott Harmon
# Available under the terms of the GNU GPL.
#

NAME="dropline-version"
VERSION="3.10.0"
REVISION="1"
DATE="2013-09-24"
DISTRIBUTOR="Dropline GNOME"
STARTPAGE="dropline-startpage-3.6-alpha.tar.bz2"
SPLASH="splash-generic.png"
PKG_ARCH="noarch"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

# gnome-version
PKG_SOURCEURL=http://ftp.gnome.org/pub/GNOME/sources/gnome-desktop/${VER_MAJ}.${VER_MIN}/gnome-desktop-${VERSION}.tar.xz
createdir ${PKG_WORKROOT}
createdir ${PKG_LOGROOT}
findtarball filename
if [ -z "${filename}" ]; then
	echo "Unable to locate ${PKG_SOURCEURL}!  Exiting..."
	die
fi
opentarball ${filename}
createdir ${PKG_STAGEROOT}${PKG_PREFIX}/share/gnome-about/
sed -e "s/<distributor>.*<\/distributor>/<distributor>$DISTRIBUTOR<\/distributor>/g" -e "s/<date>.*<\/date>/<date>$DATE<\/date>/g" ${PKG_SRCROOT}/gnome-version.xml > ${PKG_STAGEROOT}${PKG_PREFIX}/share/gnome-about/gnome-version.xml

# Webpage
createdir ${DLG_SCRATCHROOT}/sources/
spewdo "cp ${DLG_ROOT}/scripts/${NAME}/${STARTPAGE} ${DLG_SCRATCHROOT}/sources/${STARTPAGE}"
opentarball ${DLG_SCRATCHROOT}/sources/${STARTPAGE}
sanifysource ${PKG_SRCROOT}
spewdo "find ${PKG_SRCROOT} -type d -exec chmod 755 {} \;"
spewdo "find ${PKG_SRCROOT} -type f -exec chmod 644 {} \;"
spewdo "createdir ${PKG_STAGEROOT}${PKG_PREFIX}/share/dropline"
spewdo "mv ${PKG_SRCROOT} ${PKG_STAGEROOT}${PKG_PREFIX}/share/dropline/home"
spewdo "cd ${PKG_STAGEROOT}${PKG_PREFIX}/share/dropline/home; ln -s start.html index.html"

# Splash
spewdo "createdir ${PKG_STAGEROOT}${PKG_PREFIX}/share/pixmaps/splash"
spewdo "install -D -m0644 ${DLG_SRCDIR}/${NAME}/${SPLASH} ${PKG_STAGEROOT}${PKG_PREFIX}/share/pixmaps/splash/gnome-splash.png"

# Finish up
analyzebinaries
finalizepackage
packagize
cleanup
