#!/bin/sh
#
# Copyright 2005 Paul Blazejowski <paulb@blazebox.homeip.net>
# Available under the terms of the GNU GPL.
#

NAME="libdaemon"
VERSION="0.14"
REVISION="1"

PKG_SOURCEURL='http://0pointer.de/lennart/projects/$NAME/$NAME-$VERSION.tar.gz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure --disable-lynx
make
makecheck
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
