#!/bin/bash
#
# Copyright 2012 Eugene Wissner <belka.ew@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="harfbuzz"
VERSION="0.9.22"
REVISION="1"

PKG_SOURCEURL='http://www.freedesktop.org/software/${NAME}/release/${NAME}-${VERSION}.tar.bz2'
PKG_SANIFYNOTOUCH="needed"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
