#!/bin/bash
#
# Copyright 2012 Bart van der Hall
# Available under the terms of the GNU GPL.
#

NAME="libisoburn"
VERSION="1.3.2"
REVISION="1"

PKG_SOURCEURL='http://files.libburnia-project.org/releases/${NAME}-${VERSION}.tar.gz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
