#!/bin/bash
#
# Copyright 2005, 2007 Dagmar d'Surreal <rivyqntzne@tznvy.pbz>
# Available under the terms of the GNU GPL.
#

NAME="cairomm"
VERSION="1.10.0"
REVISION="2"

PKG_SOURCEURL='http://cairographics.org/releases/$NAME-$VERSION.tar.gz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cxxflags "$PKG_CFLAGS -lcairo"
prepare
analyzesource
configure --without-libstdc-doc
make
makecheck
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
