#!/bin/bash
#
# Copyright 2012 Tyrael <tyrael@droplinegnome.org>
# Available under the terms of the GNU GPL.
#

NAME="clutter-gtk"
VERSION="1.4.4"
REVISION="1"

PKG_SOURCEURL='$DLG_GNOMEMIRROR/$NAME/${VER_MAJ}.${VER_MIN}/$NAME-$VERSION.tar.xz'
PKG_SANIFYNOTOUCH="UFFFF"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
