#!/bin/bash
#
# Copyright 2004 Dagmar d'Surreal <rivyqntzne@tznvy.pbz>
# Available under the terms of the GNU GPL.
#

NAME="librsvg"
VERSION="2.40.1"
REVISION="1"

PKG_SOURCEURL='${DLG_GNOMEMIRROR}/$NAME/$VER_MAJ.$VER_MIN/$NAME-$VERSION.tar.xz'
PKG_LDCONFIGSOONER='yes'
PKG_SANIFYNOTOUCH='yes'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
