#!/bin/bash
#
# Copyright 2012 Eugene Wissner <belka.ew@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="ragel"
VERSION="6.8"
REVISION="2"

PKG_SOURCEURL='http://www.complang.org/${NAME}/${NAME}-${VERSION}.tar.gz'
PKG_NEEDSTATIC="configure: WARNING: unrecognized options: --disable-static"
PKG_SANIFYNOTOUCH="owwww nooooooo"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
