#!/bin/bash
#
# Copyright 2012 Eugene Wissner <belka.ew@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="gnome-themes-standard"
VERSION="3.10.0"
REVISION="1"

PKG_SOURCEURL='http://download.gnome.org/sources/${NAME}/${VER_MAJ}.${VER_MIN}/${NAME}-${VERSION}.tar.xz'
PKG_SANIFYNOTOUCH="Pufff"

PKG_PATCH[0]="gnome-themes-standard-3.6-gtk_2_0_gtkrc_direction.patch"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare

applypatch 0 1

analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
