#!/bin/bash
#
# Copyright 2013 Bart van der Hall
# Available under the terms of the GNU GPL.
#

NAME="gnome-js-common"
VERSION="0.1.2"
REVISION="3"

PKG_SOURCEURL='http://download.gnome.org/sources/${NAME}/${VER_MAJ}.${VER_MIN}/${NAME}-${VERSION}.tar.bz2'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
