#!/bin/bash
#
# Copyright 2012 Eugene Wissner <belka.ew@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="yelp-xsl"
VERSION="3.8.1"
REVISION="1"

PKG_SOURCEURL='http://ftp.gnome.org/pub/GNOME/sources/${NAME}/${VER_MAJ}.${VER_MIN}/${NAME}-${VERSION}.tar.xz'
PKG_SANIFYNOTOUCH="cannot parse msgs.xsl"
PKG_NEEDSTATIC="unrecognized options: --disable-static"
PKG_ARCH="noarch"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

prepare
analyzesource
configure
make
makeinstall

# Putting pkgconfig in its place
createdir $PKG_STAGEROOT$PKG_PREFIX/lib$LIBSUFFIX
spewdo "mv $PKG_STAGEROOT$PKG_DATADIR/pkgconfig $PKG_STAGEROOT$PKG_PREFIX/lib$LIBSUFFIX"

tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
