#!/bin/bash
#
# Copyright 2012 Eugene Wissner <belka.ew@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="libwacom"
VERSION="0.7.1"
REVISION="2"

PKG_SOURCEURL='http://${DLG_SFMIRROR}.dl.sourceforge.net/sourceforge/linuxwacom/${NAME}/${NAME}-${VERSION}.tar.bz2'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
