#!/bin/bash
#
# Copyright 2012 Bart van der Hall
# Available under the terms of the GNU GPL.
#

NAME="libchamplain"
VERSION="0.12.7"
REVISION="1"

PKG_SOURCEURL='$DLG_GNOMEMIRROR/$NAME/$VER_MAJ.$VER_MIN/$NAME-$VERSION.tar.xz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure
make
makeinstall
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
