#!/bin/bash
#
# Copyright 2013 Bart van der Hall <bartgymnast@hotmail.com>
#

NAME="gmime"
VERSION="2.6.19"
REVISION="1"

PKG_SOURCEURL='$DLG_GNOMEMIRROR/${NAME}/${VER_MAJ}.${VER_MIN}/${NAME}-${VERSION}.tar.xz'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure --disable-mono
	--enable-gtk-doc
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
